Document: canaima-webapps
Title: Debian canaima-webapps Manual
Author: <insert document author here>
Abstract: This manual describes what canaima-webapps is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/canaima-webapps/canaima-webapps.sgml.gz

Format: postscript
Files: /usr/share/doc/canaima-webapps/canaima-webapps.ps.gz

Format: text
Files: /usr/share/doc/canaima-webapps/canaima-webapps.text.gz

Format: HTML
Index: /usr/share/doc/canaima-webapps/html/index.html
Files: /usr/share/doc/canaima-webapps/html/*.html
